hello yes

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -33,11 +33,12 @@ jobs:
         run: |
             sudo apt-get update
             sudo apt-get install -y gnupg ca-certificates curl
-            curl -1sLf 'https://packages.redpanda.com/public/redpanda/gpg.237f0cf8.key' | sudo gpg --dearmor -o /usr/share/keyrings/redpanda-keyring.gpg
+            curl -fsSL 'https://packages.redpanda.com/public/redpanda/gpg.237f0cf8.key' -o redpanda.gpg || (echo "Failed to download key" && exit 1)
+            file redpanda.gpg
+            sudo gpg --dearmor -o /usr/share/keyrings/redpanda-keyring.gpg redpanda.gpg
             echo "deb [signed-by=/usr/share/keyrings/redpanda-keyring.gpg] https://packages.redpanda.com/public/redpanda/deb/any any main" | sudo tee /etc/apt/sources.list.d/redpanda.list
             sudo apt-get update
             sudo apt-get install -y rpk
-            which rpk
             rpk version
           
       - name: Run PySpark job
